openapi: 3.0.3
info:
  title: Customers API
  description: Customers API
  version: 0.0.1
servers:
  - url: 'https'
paths:
  /customer:
    post:
      operationId: createCustomer
      summary: Creates a new customer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreationRequest'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerCreationResponse'
components:
  schemas:
    CustomerCreationRequest:
      discriminator:
        propertyName: type
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          description: Customer's first name.
          example: James
        lastName:
          type: string
          description: Customer's last name.
          example: Doe
    CustomerCreationResponse:
      discriminator:
        propertyName: type
      type: object
      required:
        - customerId
      properties:
        customerId:
          type: string
          description: Customer's ID.
          example: df63577b-e0bd-4eb9-b900-be227f272cea
  
